### ISSUE TITLE
Strip PropTypes from production builds

### ISSUE THREAD

**Issue by ziir** [Gandi/babel-preset-gandi#8]
Though we use Flow almost everywhere, there are still quite a lot of PropTypes left in our production bundles.

In a typical production bundle, `.propTypes` search gives ~150 occurences.

We'd gain precious bytes by using a plugin such as `babel-plugin-transform-react-remove-prop-types` in production builds while we progressively get rid of propTypes alltogether.

**Comment by pascalduez** [comment]
This could be easily done in our Apps webpack config. Just add that plugin for the production build.
But I'm afraid the size gain might be negligible.  
Especially if we envision that they should progressively be removed anyway. (Flow, new context API).

For libs it's not really worst it.  
`node_modules` are excluded from the `babel-loader` (for good reasons I guess). 
So if we add it here, there won't be proptypes for dev, which is the main goal of proptypes.
As for libs shipping a dev and prod versions that feels like a lot of complexity ahead for again small gains. 

To me the real size gain we can have are:

- React 16
- Webpack 4
- Babel 7 (smaller produced code)
- ESM everywhere
- Maybe Rollup (at least on large libs like ui) (already tested [here)(https://github.com/pascalduez/react-module-boilerplate/blob/master/rollup.config.js))
- https://github.com/GoogleChromeLabs/webpack-libs-optimizations
- ...

**Comment by ziir** [comment]
Yeah, I forgot about our libs...

But, about:
> node_modules are excluded from the babel-loader (for good reasons I guess).

If we move forward with https://github.com/Gandi/babel-preset-gandi/pull/5

Then we will apply babel-loader to all our internal libraries in our bundles compilation.
So applying this plugin only in bundle compilation will result in propTypes being stripped:

- from the app code
- from our libraries code

So we can use this plugin in our webpack config today, and it'll be ~really worth it the day we tackle https://github.com/Gandi/babel-preset-gandi/pull/5

Thanks for sharing your insights, we definitely to get on these

**Comment by pascalduez** [comment]
> Then we will apply babel-loader to all our internal libraries in our bundles compilation.

I'm concerned about build time, especially in dev, but everything's open.

Food for thoughts https://github.com/facebook/create-react-app/issues/1125

**Comment by ziir** [comment]
I think there's no reason for us to compile the legacy bundle in development, so build time increase should not be an issue.

The main thing I'm gathering from these discussions is that applying `babel-loader` to the entire `node_modules` might not be safe, which I would agree.
We will only need to apply it to `@gandi` scoped packages, over which we have control.

**Comment by ziir** [comment]
Closing this as no longer relevant.

We are applying `babel-plugin-transform-react-remove-prop-types` on a limited set of node_modules packages, during the production client-side bundle compilation, with little gains.
